### PR TITLE
Add SonarQube to jsheroes #288

### LINKED ISSUE #288: Add Continuous Code Quality with SonarQube
https://sonarcloud.io provides continuous code quality as a free tier, and I thought that JSHeroes website should benefit from it.

### PR DESCRIPTION
**Pull request by jonattfin**
Partial Fix #288 

The build is failing due to the missing token / step 1 below.

TODO:
1) define token in repo  (step 2 from here: https://docs.travis-ci.com/user/sonarcloud/)
2) add badge with sonar cloud status (EG: https://stackoverflow.com/questions/49066014/sonarcloud-badge-on-github)

### CODE REVIEW

**Comment by danielmocan** [comment]
@alexnm can you please set sonarqube on travis pipeline when you have time

**Comment by alexnm** [comment]
@danielmocan from where do I get the value of the token?

**Comment by danielmocan** [comment]
@alexnm I sent you a PM on Slack with the token

**Comment by alexnm** [comment]
@danielmocan added

**Pull request merged**
