### PR TITLE
create contact form #213

### PR DESCRIPTION
**Pull request by jonattfin**
Fixes: [#213](https://github.com/jsheroes/jsheroes.io/issues/213)
For sending emails I've used https://sendgrid.com

My concerns:
- exposing the POST /formContact without any authentication, it's not that big issue in the end as it's just a proxy to the email provider.
- I should have done directly the call from the client / but i had problems testing it... this way & this worked and beside.. we're exposing the token.
- I've added also passport js middleware... I thought is good to have it.
- I guess the API token shouldn't be added in the code but in a environment variable

What do you think?

### CODE REVIEW

**Comment by danielmocan** [comment]
Thank you @jonattfin it looks good.
@alexnm can we add an environment variable on now server ? If we, we should get another api key that does not go through github ( through a merge request )

**Comment by alexnm** [comment]
@danielmocan ping me on slack when you have time to discuss this

**Comment by jonattfin** [comment]
@alexnm, @danielmocan can I help with something?

**Comment by danielmocan** [comment]
@jonattfin no, I will merge it, and will see where we can add the api key

**Pull request merged**
