### PR TITLE
Code of conduct page redesign

### PR DESCRIPTION
**Pull request by ciprian-iacob**
Implemented the redesign of code of conduct page and got rid of the unused CSS.

Issue -> #214

### CODE REVIEW

**Comment by alexnm** [comment]
@ciprian-iacob great work, you just need to merge master into this branch as there's a conflict (I assume) from the links updates on another branch.

also, I would suggest we add some highlights on the second part of the CoC (cc @oana-sipos what do you think? what should we highlight in the last paragraphs?)

screenshot 2018-11-05 at 22 05 55

**Comment by oana-sipos** [comment]
@alexnm  Yes, I agree. I did highlight in my own PR some paragraphs, so feel free to do so @ciprian-iacob.
P.S. Really sorry for the very late reply, too much on my plate 🍽

**Comment by danielmocan** [comment]
@ciprian-iacob Can you please fix the merge conflicts, I would like to merge your PR

**Comment by ciprian-iacob** [comment]
Hello, guys - sorry for my late reply but I was on holiday the previous week.

@alexnm - Added highlights as on Oana's PR.
screen shot 2018-11-12 at 20 47 50

@danielmocan - Fixed PR conflicts.

If there are any other issues, please let me know.

Thanks.

**Pull request merged**
