### PR TITLE
Photo galleries from each year #215

### PR DESCRIPTION
**Pull request by jonattfin**
Fixes: #215

The respnsive versions can be viewed here: https://sizzy.co/?url=https%3A%2F%2Fjsheroesio-uxcsdxrznx.now.sh%2F (doesn't work in firefox / but works in chrome) 

or

https://drive.google.com/file/d/1S79YLIZIIrcWvmwNeY4azk4-5QOp19TJ/view
https://drive.google.com/open?id=1SaUBJOEnADVZzY1l_JlOf3XKnuy3XyOT

Notes

- In the original design while hovering a image, an blue border was shown, but i didn't do it, because it would move also the other images and I didn't know to fix that.
- I don't find it easy to work on designs as images... so I've created ticket #279 in which I propose to use Zeplin).
- I've just started with CSS (I'm junior so to say), so responsiveness is nearly 100%.

Also

-  I've installed uuid - I needed a way to generate unique keys.
-  I've done also a bit of refactoring on 2017 / 2018 & index.js pages. I've seen a lot of repeating code there, so i made it a bit DRY. Also I've used directly the stores from their year folder, and not through the parent index. Why? It doesn't make sense from 2018... to wait the module loader to load data for 2017, or 2019 etc (I've created ticket #278 in which I propose a refactoring of the code).

### CODE REVIEW

**Comment by jonattfin** [comment]
@alexnm no alex is not, it's a feature :-) I'll take a look at the media queries...

**Comment by jonattfin** [comment]
@alexnm what's your laptop resolution?

**Comment by alexnm** [comment]
it's a 13" macbook, retina display, resolution is 2560 x 1600, but screen width is around 1200-1300px

**Comment by jonattfin** [comment]
@alexnm please take another look now.

**Comment by alexnm** [comment]
@jonattfin  now it's not ok on mobile :) also noticed on large resolutions (>1400px) that the side text is hidden. I think the container of the grid should have a max size of 100% based on the screen width at all times, but unfortunately I don't have time these days to have a look
screenshot 2018-12-28 at 11 52 07

**Comment by jonattfin** [comment]
@alexnm ok ... i will try to see what i can do

**Pull request merged**
